### ISSUE TITLE
Bug: can't parse maxResults when not specified

### ISSUE THREAD

**Issue by raulb** [conduitio-labs/conduit-connector-azure-storage#101]
### Bug description

Testing this connector locally in a conduit pipeline, when not providing the optional configuration field `maxResults`, conduit throws an error when trying to parse. Here's an example log:

```
2024-05-16T14:28:53+00:00 ERR node stopped error="node azure-to-log:example.in stopped with error: could not open source connector: could not configure source connector plugin: configuration error: failed to parse \"maxResults\" config value: strconv.ParseInt: parsing \"4s8\": invalid syntax" component=pipeline.Service node_id=azure-to-log:example.in stack=[{"file":"/Users/rb/code/conduitio/conduit/pkg/pipeline/lifecycle.go","func":"github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func2","line":583},{"file":"/Users/rb/code/conduitio/conduit/pkg/pipeline/stream/source.go","func":"github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run","line":110},{"file":"/Users/rb/code/conduitio/conduit/pkg/connector/source.go","func":"github.com/conduitio/conduit/pkg/connector.(*Source).configure","line":287},{"file":"/Users/rb/code/conduitio/conduit/pkg/plugin/connector/standalone/v1/client.go","func":"github.com/conduitio/conduit/pkg/plugin/connector/standalone/v1.unwrapGRPCError","line":165}]
```

**Workaround:** Provide this configuration field manually.

### Steps to reproduce

1. Build binary for this connector
2. Use it as a source
3. Don't specify optional configuration field `maxResults`
4. See the error

Example of a pipeline using this connector as a source that will expose the error:

```yaml
version: 2.2
pipelines:
  - id: azure-to-log
    # run pipeline on startup
    status: running
    description: >
      Example pipeline reading from file "example.in" and writing into file "example.out".

    connectors:
      - id: example.in
        type: source
        # use the built-in file plugin as the source
        plugin: azure-storage
        settings:
          connectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"
          containerName: "test"
      - id: example.out
        type: destination
        # use the built-in file plugin as the destination
        plugin: file
        settings:
          # write data to example.out
          path: ./example.out
          # output the raw payload as a string
          sdk.record.format: template
          sdk.record.format.options: '{{ printf "%s" .Payload.After }}'
```

### Version

v0.3.0
